---
- name: Update apt
  apt: update_cache=yes
  hosts: all

- name: Install dependencies

    - name: Install kvm
      apt: 
        update_cache: yes
        pkg:
          - qemu-kvm 
          - libvirt-daemon-system 
          - libvirt-clients 
          - bridge-utils
