---
- name: Install nice to have packages
  hosts: all
  tasks:
    - name: Install software
      apt: 
        update_cache: yes
        pkg:
          - jq 
          - mosh 
          - tmux 
          - screen 
          - fail2ban 
          - zsh 
          - iperf3 
          - htop 
          - pandoc 
          - fonts-inconsolata 
          - fonts-open-sans 
          - fonts-roboto 
          - imagemagick 
          - iotop 
          - vim
          - speedtest-cli
          - wget 
          - curl 
          - vim 
          - wget 
          - curl 
          - python3 
          - python3-pip 
          - apt-transport-https 
          - software-properties-common
