---
- name: Install nice to have desktop packages
  hosts: all
  tasks:
    - name: Install software
      apt: 
        update_cache: yes
        pkg:
          - libreoffice
          - openscad 
          - blender 
          - gparted 
          - krita 
          - firefox