- name: Install GIS packages
  hosts: all 
  tasks:
    - name: Install software
      apt: 
        update_cache: yes
        pkg:
          - python3-pip
          - ffmpeg
          - git 
          - python3-virtualenv
- name: Install Python Packages
  ansible.builtin.pip:
    name:
      - torch
      - torchvision
      - torchaudio
      - jupyter
      - git+https://github.com/openai/whisper.git 
      - pyannote.audio
    virtualenv: /root/.pyenv
